spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: collector
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
weekly-updater:
  publisher: panini-manga-mx
  titles: bungo-stray-dogs,de-yakuza-a-amo-de-casa,por-tu-culpa-no-puedo-respirar,the-elusive-samurai,re-zero-chapter-four,junjo-romantica,shangri-la-frontier,el-canto-de-la-noche,kemono-jihen,one-piece,blue-exorcist,overlord,girlfriend-girlfriend
  images:
    path: D:\\Documents\\imagesCollector\\
  datasource:
    h2:
      jdbc-url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    postgres:
      jdbc-url: jdbc:postgresql://host.docker.internal:5432/collector
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver